name: CI Angular app through GitHub Actions
on:
  push:
    branches: [ "release"]
  pull_request:
    branches: [ "release"]
jobs:
  release_ci_cd:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 18.x
        uses: actions/setup-node@v1
        with:
          node-version: 18.x

      - name: list code
        run: ls -la

      - name: Setup -npm install
        run: npm ci

      - name: list node_modules
        run: ls node_modules

      - name: Test
        run: |
          npm test -- --no-watch --no-progress --browsers=ChromeHeadlessCI
